# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryo Mayes
email: ryomayes@gmail.com
aboutme:

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryomayes.com" # the base hostname & protocol for your site
username: ryomayes
# Build settings
markdown: kramdown
